-- Spanish site, Phase 1 (see PLAN.md). NOT YET RUN -- review first.
-- Purely additive: one new table, nothing on "Article" changes. Safe to re-run.
-- Rollback: DROP TABLE "ArticleTranslation";

CREATE TABLE IF NOT EXISTS "ArticleTranslation" (
  "id"         text PRIMARY KEY,
  "articleId"  text NOT NULL REFERENCES "Article"("id") ON DELETE CASCADE,
  "locale"     text NOT NULL,
  "title"      text,
  "summary"    text,
  "body"       text,
  "slug"       text,
  "sourceHash" text NOT NULL,
  "status"     text NOT NULL DEFAULT 'translated',
  "attempts"   integer NOT NULL DEFAULT 0,
  "lastError"  text,
  "model"      text,
  "createdAt"  timestamp(3) NOT NULL DEFAULT now(),
  "updatedAt"  timestamp(3) NOT NULL DEFAULT now()
);

-- One translation per article per language; one slug per language.
CREATE UNIQUE INDEX IF NOT EXISTS "ArticleTranslation_articleId_locale_key" ON "ArticleTranslation" ("articleId", "locale");
CREATE UNIQUE INDEX IF NOT EXISTS "ArticleTranslation_locale_slug_key" ON "ArticleTranslation" ("locale", "slug");
CREATE INDEX IF NOT EXISTS "ArticleTranslation_locale_status_idx" ON "ArticleTranslation" ("locale", "status");

-- Per-language full-text search. Generated by Postgres itself (like
-- "Article"."searchVector"), picking the text-search config from the row's
-- locale; a new language adds a WHEN branch here.
ALTER TABLE "ArticleTranslation" ADD COLUMN IF NOT EXISTS "searchVector" tsvector
  GENERATED ALWAYS AS (
    to_tsvector(
      (CASE "locale" WHEN 'es' THEN 'spanish' ELSE 'simple' END)::regconfig,
      coalesce("title", '') || ' ' || coalesce("summary", '') || ' ' || coalesce("body", '')
    )
  ) STORED;
CREATE INDEX IF NOT EXISTS "ArticleTranslation_searchVector_idx" ON "ArticleTranslation" USING GIN ("searchVector");
